### ISSUE TITLE
Add small icon to Medical Appointment Notification

### ISSUE THREAD

**Issue by piotrgos45** [michalmobi/PatientAssistant#61]
Application crash after editing appointment. It's an issue to fix this error.

![image](https://user-images.githubusercontent.com/85040722/213191041-a1135a44-9975-4db5-814a-437489af5041.png)

**Comment by michalmobi** [comment]
@piotrgos45 please provide some description here

**Comment by michalmobi** [comment]
@piotrgos45 thank you. Just one note: next time please just paste the error text instead of inserting a screenshot. Then it will take less space and will be searchable in github (in case someone in the future wanted to check if similar errors already appeared). We can't search for text in images.
